import = ["/Users/nathantapsas/.config/alacritty/themes/gruvbox_dark.toml"]

[env]
TERM="xterm-256color"

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
decorations = "none"

[window.padding]
x = 4
y = 4

[shell]
program = "/bin/bash"
args = ["--login"]
