format = """
$username\
$hostname\
:$directory\
$fill\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$line_break\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[fill]
symbol="'"
disabled=false

[username]
show_always = true
style_user = "color_orange"
style_root = "color_orange"
format = '[$user]($style)'

[directory]
style = "color_yellow"

[character]
success_symbol = "[❯](color_blue)"
error_symbol = "[❯](color_red)"
vimcmd_symbol = "[❮](color_green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "color_aqua"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "color_yellow"

[python]
format = '[$virtualenv]($style) '
style = "bright-black"
